/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ModalPopup: typeof import('./components/Modal/Popup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableDrawer: typeof import('./components/Table/Drawer.vue')['default']
    TableDropdown: typeof import('./components/Table/Dropdown.vue')['default']
    TableForm: typeof import('./components/Table/Form.vue')['default']
    Text: typeof import('./components/Text.vue')['default']
  }
}
